#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar height=36 \
    blur_radius=30 \
    position=top \
    sticky=on \
    padding_left=10 \
    padding_right=10

sketchybar --default icon.font="SF Pro:Semibold:12.0" \
    icon.color=$ITEM_COLOR \
    label.font="SF Pro:Semibold:12.0" \
    label.color=$ITEM_COLOR \
    background.color=$ACCENT_COLOR \
    background.corner_radius=10 \
    background.height=20 \
    padding_left=4 \
    padding_right=4 \
    icon.padding_left=6 \
    icon.padding_right=3 \
    label.padding_left=3 \
    label.padding_right=6

source $ITEM_DIR/spaces.sh

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
