###########################################################
###                Basic  configuration                ####
###########################################################

source = ~/.config/hypr/monitors.conf

device {
    name = apple-spi-keyboard
    kb_options = altwin:swap_alt_win
}

device {
    name = apple-spi-trackpad
    natural_scroll = true
}

$mod = SUPER

$brightness_control = ~/.config/hypr/brightness_control.sh
$keyboard_brightness_control = ~/.config/hypr/keyboard_brightness_control.sh

###########################################################
####                     End                           ####
###########################################################



###########################################################
####               Autostart applications              ####
###########################################################

exec-once = hyprdynamicmonitors run --disable-power-events --enable-lid-events

###########################################################
####                    End                            ####
###########################################################



###########################################################
####              Start applications                   ####
###########################################################

bind = $mod, f2, exec, chromium-browser

bind = , XF86MonBrightnessDown, exec, $brightness_control down
bind = , XF86MonBrightnessUp, exec, $brightness_control up

bind = $mod shift, z, exec, $keyboard_brightness_control down
bind = $mod shift, x, exec, $keyboard_brightness_control up

###########################################################
####                    End                            ####
###########################################################



###########################################################
####                 Window rules                      ####
###########################################################


windowrule = opacity 1.0 override 1.0 override, match:class chromium-browser
windowrule = opacity 1.0 override 1.0 override, match:class mpv
windowrule = opacity 1.0 override 1.0 override, match:class org.pwmt.zathura

##########################################################
####                    End                            ####
###########################################################
