###########################################################
###                Basic  configuration                ####
###########################################################

monitor = DP-1, 3840x2160@144, 0x0, 2

$mod = SUPER

###########################################################
####                     End                           ####
###########################################################



###########################################################
####               Autostart applications              ####
###########################################################

exec-once = easyeffects --service-mode --hide-window

###########################################################
####                    End                            ####
###########################################################



###########################################################
####              Start applications                   ####
###########################################################

bind = $mod, f2, exec, chromium

bind = $mod, f4, exec, spotify

###########################################################
####                    End                            ####
###########################################################



###########################################################
####               Spotify control                     ####
###########################################################

bind = $mod ctrl, up,    exec, dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
bind = $mod ctrl, left,  exec, dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
bind = $mod ctrl, right, exec, dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

###########################################################
####                    End                            ####
###########################################################



###########################################################
####                 Window rules                      ####
###########################################################

windowrule = opacity 1.0 override 1.0 override, match:class chromium
windowrule = opacity 1.0 override 1.0 override, match:class mpv
windowrule = opacity 1.0 override 1.0 override, match:class org.pwmt.zathura

###########################################################
####                    End                            ####
###########################################################
