# ~/.config/hypr/hyprlock.conf

background {
    color = rgb(1e1e2e)
}

input-field {
    size = 300 50
    outline_thickness = 2
    outer_color = rgb(cdd6f4)
    inner_color = rgb(313244)
    font_color = rgb(cdd6f4)
    placeholder_text = Password
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

label {
    text = $TIME
    font_size = 64
    color = rgb(cdd6f4)
    position = 0, 100
    halign = center
    valign = center
}

label {
    text = 因为是败家之犬所以只能拥有回忆
    font_family = LXGW WenKai Medium
    font_size = 40
    color = rgb(cdd6f4)
    position = 0, 70
    halign = center
    valign = bottom
}
